# Generated by Django 3.2.16 on 2024-10-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0021_delete_communityrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyrole',
            name='taggable',
            field=models.BooleanField(default=False),
        ),
    ]
